
apiVersion: v1
kind: Service
metadata:
  name: finbanking-api-svc
  labels:
    app: finbanking-api
spec:
  type: ClusterIP
  selector:
    app: finbanking-api
  ports:
  - port: 80
    targetPort: 8080